name: Sync Maison01.ics depuis VRBO

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:      # Pour exécuter manuellement si besoin

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v3

    - name: Télécharger le fichier VRBO
      run: |
        curl -s -L "http://www.vrbo.com/icalendar/3fdfd900b0ec4547aae7c1dac753f67e.ics?nonTentative" -o raw.ics

    - name: Nettoyer les infos sensibles (noms clients)
      run: |
        sed 's/SUMMARY:.*/SUMMARY:Réservé/g' raw.ics > Maison01.ics

    - name: Commit et push si modifié
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add Maison01.ics
        git diff --quiet && echo "Pas de changement" || git commit -m "Mise à jour automatique Maison01.ics"
        git push
