name: Sync Maison01.ics depuis VRBO

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-ics:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v3

    - name: Télécharger le .ics VRBO
      run: |
        curl -sSfL -o raw.ics "http://www.vrbo.com/icalendar/3fdfd900b0ec4547aae7c1dac753f67e.ics?nonTentative"
        if [ ! -s raw.ics ]; then
          echo "❌ Le fichier raw.ics est vide !"
          exit 1
        fi
        echo "✅ raw.ics téléchargé - taille : $(wc -c < raw.ics) octets"

    - name: Générer Maison01.ics propre
      run: |
        {
          echo "BEGIN:VCALENDAR"
          echo "VERSION:2.0"
          echo "CALSCALE:GREGORIAN"
          echo "PRODID:-//Optimind//Calendrier Maison01//FR"
          echo "X-WR-CALNAME:Calendrier Maison01"
          echo "X-WR-TIMEZONE:Europe/Paris"
          grep -E "^(BEGIN:VEVENT|UID:|DTSTAMP:|DTSTART.*|DTEND.*|SUMMARY:|END:VEVENT)" raw.ics \
            | sed -E 's/SUMMARY:Reserved.*/SUMMARY:Réservé - Maison01/' \
            | sed -E 's/SUMMARY:Blocked.*/SUMMARY:Bloqué/' 
          echo "END:VCALENDAR"
        } > Maison01.ics
        echo "✅ Maison01.ics généré - taille : $(wc -c < Maison01.ics) octets"

    - name: Segmenter les longues lignes (compatibilité)
      run: |
        fold -w 75 Maison01.ics > Maison01_tmp.ics && mv Maison01_tmp.ics Maison01.ics

    - name: Commit si modification
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add Maison01.ics
        if ! git diff --cached --quiet; then
          git commit -m "🔁 Mise à jour automatique Maison01.ics"
          git push
          echo "✅ Fichier mis à jour et envoyé."
        else
          echo "ℹ️ Aucun changement détecté dans Maison01.ics."
        fi


